{% set name = "httpagentparser" %}
{% set version = "1.9.2" %}
{% set sha256 = "a190dfdc5e63b2f1c87729424b19cbc49263d6a1fb585a16ac1c9d9ce127a4bf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt


requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - httpagentparser

about:
  home: http://shon.github.com/httpagentparser
  license: MIT
  license_file: LICENSE.txt
  summary: Extracts OS Browser etc information from http user agent string
  license_family: MIT
  # license_file: LICENSE.txt  # https://github.com/shon/httpagentparser/pull/76

extra:
  recipe-maintainers:
    - mariusvniekerk
